version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      kafka:
        ipv4_address: 172.56.0.2
  broker_producer:
    image: wurstmeister/kafka
    ports:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.56.0.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    deploy:
      replicas: 3
    networks:
      kafka:
        ipv4_address: 172.56.0.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  broker_customer:
    image: wurstmeister/kafka
    ports:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.56.0.4
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      kafka:
        ipv4_address: 172.56.0.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  kafka:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.56.0.0/16
