version: "3.4"
services:
  redis.master:
    image: redis:3.2-alpine
    volumes:
       - /data/redis/conf:/etc/redis
       - /data/redis/data:/usr/data
   redis.1:
     image: redis:3.2-alpine
     volumes:
       - /data/redis/conf:/etc/redis

